/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.provacalculadora;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollBar1 = new javax.swing.JScrollBar();
        lbTitulo = new javax.swing.JLabel();
        tfP1 = new javax.swing.JTextField();
        lbValor2 = new javax.swing.JLabel();
        lbValor1 = new javax.swing.JLabel();
        lbTitulo1 = new javax.swing.JLabel();
        lbTitulo2 = new javax.swing.JLabel();
        lbTitulo3 = new javax.swing.JLabel();
        btComparativo = new javax.swing.JButton();
        tfP3 = new javax.swing.JTextField();
        tfP8 = new javax.swing.JTextField();
        tfP9 = new javax.swing.JTextField();
        tfP10 = new javax.swing.JTextField();
        lbTitulo4 = new javax.swing.JLabel();
        lbTitulo5 = new javax.swing.JLabel();
        lbTitulo6 = new javax.swing.JLabel();
        lbTitulo7 = new javax.swing.JLabel();
        lbTitulo8 = new javax.swing.JLabel();
        lbTitulo9 = new javax.swing.JLabel();
        lbTitulo10 = new javax.swing.JLabel();
        lbTitulo11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTitulo12 = new javax.swing.JLabel();
        lbTitulo13 = new javax.swing.JLabel();
        btComparativo1 = new javax.swing.JButton();
        tfP4 = new javax.swing.JTextField();
        tfP5 = new javax.swing.JTextField();
        tfP6 = new javax.swing.JTextField();
        lbTitulo15 = new javax.swing.JLabel();
        lbTitulo16 = new javax.swing.JLabel();
        lbTitulo17 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Camigas");

        tfP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfP1.setText("Quantos produtos?");
        tfP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP1ActionPerformed(evt);
            }
        });

        lbValor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValor2.setText("VALOR");

        lbValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValor1.setText("VALOR");

        lbTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(0, 51, 102));
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo1.setText("Camigas");

        lbTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo2.setForeground(new java.awt.Color(0, 51, 102));
        lbTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo2.setText("Concorrentes");

        lbTitulo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo3.setForeground(new java.awt.Color(0, 51, 102));
        lbTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo3.setText("Comparativo");

        btComparativo.setText("Comparar");
        btComparativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComparativoActionPerformed(evt);
            }
        });

        tfP3.setText("Preço");
        tfP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP3ActionPerformed(evt);
            }
        });

        tfP8.setText("Preço");
        tfP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP8ActionPerformed(evt);
            }
        });

        tfP9.setText("Frete");
        tfP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP9ActionPerformed(evt);
            }
        });

        tfP10.setText("Frete");
        tfP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP10ActionPerformed(evt);
            }
        });

        lbTitulo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo4.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo5.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo6.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo7.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo8.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo8.setText("Aproveitamento por carregameto");

        lbTitulo9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo9.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo9.setText("Ganhos por produto");

        lbTitulo10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo10.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo10.setText("Ganhos por mês ");

        lbTitulo11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo11.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo11.setText("Ganhos por ano ");

        jLabel1.setText("Busca rápida:");

        lbTitulo12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo12.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo12.setText("Quantas camisas deseja?");

        lbTitulo13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo13.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo13.setText("Valor máximo?(valor mín de R$5.00)");

        btComparativo1.setText("Buscar");
        btComparativo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComparativo1ActionPerformed(evt);
            }
        });

        tfP4.setText("5");
        tfP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP4ActionPerformed(evt);
            }
        });

        tfP5.setText("0");
        tfP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP5ActionPerformed(evt);
            }
        });

        tfP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfP6.setText("Estado(Sigla em MAIÚSCULO)");
        tfP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP6ActionPerformed(evt);
            }
        });

        lbTitulo15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo15.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo16.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTitulo17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitulo17.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTitulo12, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTitulo13)
                                    .addComponent(tfP6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btComparativo1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(tfP5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(tfP4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTitulo16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTitulo17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbTitulo15, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbTitulo7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTitulo8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTitulo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(lbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfP1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfP9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(btComparativo)))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfP10)
                                            .addComponent(tfP8)
                                            .addComponent(lbValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addComponent(tfP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lbTitulo12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btComparativo1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbValor1)
                                .addComponent(btComparativo)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tfP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lbTitulo8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitulo15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitulo16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitulo17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo11)
                .addGap(2, 2, 2)
                .addComponent(lbTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP1ActionPerformed

    private void btComparativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComparativoActionPerformed
        // TODO add your handling code here:
        Integer qnumero = Integer.valueOf(tfP1.getText());
        Double num1 = Double.valueOf(tfP3.getText());
        Double num2 = Double.valueOf(tfP8.getText());
        Double fre1 = Double.valueOf(tfP9.getText());
        Double fre2 = Double.valueOf(tfP10.getText());
        Double a = (num1 * qnumero)+fre1;
        Double b = (num2 * qnumero)+fre2;
        lbValor1.setText(String.valueOf(a));
        lbValor2.setText(String.valueOf(b));
        
        lbTitulo4.setText(String.valueOf(b-a));
        lbTitulo5.setText(String.valueOf(num2-num1));
        lbTitulo6.setText(String.valueOf((b-a)*30));
        lbTitulo7.setText(String.valueOf((b-a)*365));


        
    }//GEN-LAST:event_btComparativoActionPerformed

    private void tfP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP3ActionPerformed

    private void tfP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP8ActionPerformed

    private void tfP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP9ActionPerformed

    private void tfP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP10ActionPerformed

    private void btComparativo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComparativo1ActionPerformed
        // TODO add your handling code here:
        Integer quantCamisa = Integer.valueOf(tfP5.getText());
        Double camisas = Double.valueOf(quantCamisa);
        Integer maxvalor = Integer.valueOf(tfP4.getText());
        Double valorcamisa = ThreadLocalRandom.current().nextDouble(5, maxvalor);
        String frete = tfP6.getText();
        Double total = 15.90+(valorcamisa * camisas);
        if (frete.equals("SP")||frete.equals("RJ")||frete.equals("MG")) {
                lbTitulo15.setText(String.format("%s válido e lhe custará \n R$15.90", frete));
                lbTitulo16.setText(String.format("R$ %.2f", valorcamisa));
                lbTitulo17.setText(String.format("R$ %.2f", total));
            }else{
            lbTitulo15.setText(String.format("%s é inválido. Sentimos muito ainda não atentemos esse estado", frete));
            }
        


        
        

        
    }//GEN-LAST:event_btComparativo1ActionPerformed

    private void tfP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP4ActionPerformed

    private void tfP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP5ActionPerformed

    private void tfP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComparativo;
    private javax.swing.JButton btComparativo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTitulo10;
    private javax.swing.JLabel lbTitulo11;
    private javax.swing.JLabel lbTitulo12;
    private javax.swing.JLabel lbTitulo13;
    private javax.swing.JLabel lbTitulo15;
    private javax.swing.JLabel lbTitulo16;
    private javax.swing.JLabel lbTitulo17;
    private javax.swing.JLabel lbTitulo2;
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JLabel lbTitulo4;
    private javax.swing.JLabel lbTitulo5;
    private javax.swing.JLabel lbTitulo6;
    private javax.swing.JLabel lbTitulo7;
    private javax.swing.JLabel lbTitulo8;
    private javax.swing.JLabel lbTitulo9;
    private javax.swing.JLabel lbValor1;
    private javax.swing.JLabel lbValor2;
    private javax.swing.JTextField tfP1;
    private javax.swing.JTextField tfP10;
    private javax.swing.JTextField tfP3;
    private javax.swing.JTextField tfP4;
    private javax.swing.JTextField tfP5;
    private javax.swing.JTextField tfP6;
    private javax.swing.JTextField tfP8;
    private javax.swing.JTextField tfP9;
    // End of variables declaration//GEN-END:variables
}
